DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS habit;
DROP TABLE IF EXISTS habit_log;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE habit(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    creator_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (creator_id) REFERENCES user(id)
);

CREATE TABLE habit_log(
    -- id INTEGER PRIMARY KEY AUTOINCREMENT, 
    log_date DATE NOT NULL,
    stat BOOLEAN,
    habitid INTEGER NOT NULL,
    PRIMARY KEY (habitid, log_date),
    FOREIGN KEY (habitid) REFERENCES habit(id)
);

